spring:
  application:
    name: travel-adviser

  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:h2:mem:users
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      model: gpt-3.5-turbo
