server:
  port: 8081
spring:
  application:
    name: travel-adviser

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/travel-gram

  datasource:
    url: jdbc:h2:mem:users
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      model: gpt-3.5-turbo